### ISSUE TITLE
Event colors on calendar, tags

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/wrh-organization#154]
Currently, the events on the calendar get some coloring based on tags. The problem is that we have 25+ tags. How should we choose colors?
1. Use the special event tags. No event should have any more than 2? special tags.
2. Do we then require a special tag?
3. Should this be another event field?
4. We could have based on these primary types (mountain bike, gravel, CX, Road, Track)

I prefer 4. Not sure the best way to implement that. I guess another field.

**Comment by aishkrish95** [comment]
I think this depends on whether events will be filter-able using the tags.
If yes, that's far too many high-level tags and we should stick to primary
types, maybe by type of cycling as you listed in #4. If no, I don't think
it would make sense to do it by color, because it's just too many. Can the
tags just be listed in a field below the description?

*Aishwarya Krishnamoorthy*
Director of Marketing and Communications, Bicycle Colorado & the Denver
Streets Partnership
Pronouns: she/her/hers
1525 Market Street, Suite 100
Denver, CO 80202
Phone: (720) 504-8515‬
bicyclecolorado.org
<https://www.bicyclecolorado.org/join-us/become-a-member/>
